### PR TITLE
Pipe to sh, rather than bash

### PR DESCRIPTION
**Pull request by rspeed**
Bash isn't installed by default on all systems, and the hashbang uses `sh` anyway.

### CODE REVIEW

**Comment by rspeed** [comment]
…huh?

**Comment by caarlos0** [comment]
I didn't do that... weird..

**Comment by caarlos0** [comment]
https://www.facebook.com/Donburgerjlle/

**Comment by caarlos0** [comment]
image

**Comment by rspeed** [comment]
Huh. Bizarre. I even made the change through the website!

**Comment by caarlos0** [comment]
oh, it's because the source is actually on antibody repo... this is generated and on every deploy travis override everything... so it was auto-closed because of that I think.

Either way, I fixed on the other repo and put you as co-author.

Thanks =D

**Comment by rspeed** [comment]
Cool, thanks!

**Pull request closed without merging**
